apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: default
  labels:
    app: service-b
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
    # - port: 3000
    #   targetPort: 3000
  selector:
    app: service-b
